name: Release (markdown)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # push di una versione canonica (es. v1.2.3) senza pre-release

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  # 1. Controlla se siamo sul branch corretto
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      is_master: ${{ steps.check.outputs.is_master }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check if tag is on master
        id: check
        run: |
          git fetch origin master
          if git branch -r --contains ${GITHUB_SHA} | grep -q "origin/master"; then
            echo "âœ… Tag ${{ github.ref }} is on master branch. Proceeding with release."
            echo "is_master=true" >> "$GITHUB_OUTPUT"
          else
            echo "âŒ Tag ${{ github.ref }} is not on master branch. Skipping release."
            echo "is_master=false" >> "$GITHUB_OUTPUT"
          fi

  # 2. Effetua la build
  build-release:
    needs: check-branch
    # Esegue questo job SOLO se l'output del job precedente Ã¨ 'true'
    if: needs.check-branch.outputs.is_master == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "categories": [
               { "title": "## â›°ï¸ Features", "labels": ["new"] },
               { "title": "## ğŸ—ï¸ Implementations", "labels": ["implement"] },
               { "title": "## ğŸ› Bug Fixes", "labels": ["fix"] },
               { "title": "## ğŸšœ Changes", "labels": ["change"] },
               { "title": "## ğŸ¯ Cover Requirements", "labels": ["cover"] },
               { "title": "## âœ¨ Refactor", "labels": ["refactor"] },
               { "title": "## ğŸ“š Documentation", "labels": ["docs"] },
               { "title": "## ğŸ¨ Styling", "labels": ["style"] },
               { "title": "## â—€ï¸ Revert", "labels": ["revert"] },
               { "title": "## âš™ï¸ Miscellaneous Tasks", "labels": ["misc"] },
               { "title": "## ğŸ’¬ Other", "labels": ["other"] },
               { "title": "## â“ Unknown", "labels": ["unknown"] },
               { "title": "## ğŸš€ Release", "labels": ["release"] }
             ],
             "ignore_labels": [
                "release",
                "ignore"
             ],
             "transformers": [
              {
                "pattern": "^[^\\(:\\s]+(\\([^\\)]+\\))?!?:\\s+([\\S]+[\\s\\S]*)",
                "target": "$2 $1"
              }
             ],
             "sort": {
                "order": "ASC",
                "on_property": "mergedAt"
             },
             "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>\n\n**Full Changelog**: [#{{FROM_TAG}}...#{{TO_TAG}}](https://github.com/#{{OWNER}}/#{{REPO}}/compare/#{{FROM_TAG}}...#{{TO_TAG}})",
              "label_extractor": [
               {
                 "pattern": "^([^\\(:\\s]+)(\\([^\\)]+\\))?(!)?:\\s+([\\S]+[\\s\\S]*)",
                 "on_property": "title",
                 "target": "$1"
               }
             ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: src/**/*
          fail_on_unmatched_files: true
          generate_release_notes: false
          tag_name: ${{ github.ref_name }}
          name: ${{github.event.repository.name}} ${{ github.ref_name }}
          body: ${{ steps.build_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
